### ISSUE TITLE
Mainnets are failing with a testnet of the same currency running

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#119]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.

## Issue
@bridgedragon has reported that when you start a mainnet of a currency while its testnet is running, some services fail.

**Comment by bridgedragon** [comment]
I think that it is caused by reusing hostnames across docker-composes.

My proposal is to rename the tags, relating them  with their network. For example, "bitcoincore" tag would become "bitcoincore-testnet" in the testnet and "bitcoincore-mainnet" in the mainnet.

The incompatibilities would be caused by using the same hostnames in the same network.
