### ISSUE TITLE
Startup Script needs to stop APIs registered with a remote node

### ISSUE THREAD

**Issue by phoenix-web3** [swapper-org/NodeChain#148]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.

## Issue

We want to stop APIs associated to a remote node. We also want to show the status of this APIs in the interface

**Comment by bridgedragon** [comment]
I think it should be possible to stop any API. This approach can be made by 'nodechain.py stop -c "CURRENCY_TO_STOP" -n "NETWORK_TO_STOP". After that, NC should look APIs started with that parameters, and stop them.

This is the most reasonable approach, because only one CURRENCY + NETWORK can be started at the same time, and this key is unique.

The confirmation asking if do you want to stop all APIs, as I think, should be also removed. If you execute that command you are supposed to know what you are doing.

**Comment by phoenix-web3** [comment]
> I think it should be possible to stop any API. This approach can be made by 'nodechain.py stop -c "CURRENCY_TO_STOP" -n "NETWORK_TO_STOP". After that, NC should look APIs started with that parameters, and stop them.
> 
> This is the most reasonable approach, because only one CURRENCY + NETWORK can be started at the same time, and this key is unique.
> 
> The confirmation asking if do you want to stop all APIs, as I think, should be also removed. If you execute that command you are supposed to know what you are doing.

It should be possible to stop any API. I'll work on it.
In the other hand, there's no confirmation  asking if you want to stop all APIs. The only confirmation you'll be asked is if you want to stop the Connector. Saying "yes" you'll be stopping every API

**Comment by bridgedragon** [comment]
Oh, okay. I did not get it. We should then parametrize it then, to be used in scripts :1st_place_medal:
