### ISSUE TITLE
Estimate fee per byte too high

### ISSUE THREAD

**Issue by hippocampusSwapper** [swapper-org/NodeChain#75]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.

## Issue

The method `getFeePerByte` always returns "1000" it's a very high fee. The method returns "1000" without taking into account the confirmations parameter, returns the same for `confirmations: 1` and `confirmations: 25`

![image (3)](https://user-images.githubusercontent.com/72935005/151771076-bae465cb-667b-46ae-b82e-f2a8c3198b2e.png)

**Comment by phoenix-web3** [comment]
After some researching, this might be a mempool error. I was testing in a local node (mainnet network) and here's the result of `estimatesmartfee`:

```sh
# bitcoin-cli -rpcuser=swapper -rpcpassword=swapper estimatesmartfee 2
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 0
}
```

There's no feerate because we need the blockchain synchronized. Once the blockchain is synchronized, bitcoind estimates the fee with the mempool  data. Here's the response of `getmempoolinfo`:

```sh
# bitcoin-cli -rpcuser=swapper -rpcpassword=swapper getmempoolinfo
{
  "loaded": true,
  "size": 0,
  "bytes": 0,
  "usage": 0,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000,
  "unbroadcastcount": 0
}
```

As we can see, this `mempoolminfee` and `minrelaytxfee` seems similar to the response of `getFeePerByte`.

Conclusion:
While the blockchain is synchronizing, we can't estimate the fee. After that, we get `"feePerByte": "1000"` because our mempool is empty and estimatesmartfee is calculating the fee with  ` "mempoolminfee": 0.00001000`

**Comment by bridgedragon** [comment]
I propose returning an error or some kind of indicator if blockchain is not synced.

If for any reason any app relies on this endpoint, it will fail if the syncing is stopped, without knowing that failed.

The solution otherwise would be to querry "/syncing" in every request, which is very expensive in the viewpoint of the server architecture.

**Comment by phoenix-web3** [comment]
Testing getfeerate from other electrum testnet server:

![imagen](https://user-images.githubusercontent.com/75782378/152011077-5e2537f2-9485-416a-9777-29eae7db3364.png)

@hippocampusSwapper

**Comment by hippocampusSwapper** [comment]
Reopen this bug because the problem has been found and needs a fix. `getFeePerByte` returns the output of RPC method `estimatesmartfee` but with this method, you obtain fee per kilobyte not fee per byte so a conversion is necessary before returning the data to clients. 

RPC docs:  https://bitcoincore.org/en/doc/0.21.0/rpc/util/estimatesmartfee/

**Comment by phoenix-web3** [comment]
According to this article: https://support.earn.com/en/articles/64966-how-do-i-calculate-my-transaction-fee

> Miners care about the fee per byte (or kilobyte). This is the total fee divided by the number of bytes in a transaction, such as 40 satoshis/byte or 0.0004 bitcoins/kilobyte. This is the most important measurement for miners.

> Warning: be careful, as some wallets only let you enter the number of satoshis/byte or bitcoins/kilobyte.  If you enter the fixed fee described above into a per-byte field, you'll probably pay more than 200 times more fee than necessary.  Instead enter the bitcoinfees.21.co recommended number of satoshis/byte (for wallets that use satoshis) or divide the recommended number of satoshis/byte by 100,000 to get the recommended number of bitcoins/kilobyte (for example, 110 / 100000 = 0.0011).

And these calculators:
https://designforbitcoins.com/btc-transaction-fee-calculator/ 
https://bitcoinfees.gitlab.io/

1KB is considered 1000B
